#!/usr/bin/env python3
"""
Healthspend Pipeline Merger
============================
Fuses the real-time MRF audit results generated by the Rust scraper
into the CMS-baseline audit_data.db, restoring a full 100-point score
range on the Facility Audit Index.

Also transfers newly scraped pricing rows so daily pipeline updates
land in the production search engine.

Score Reconstruction (100-point scale):
  CMS Baseline  (from ingest.py):  0–100 pts
    • Measured via Star Rating, Patient Experience, Safety, Mortality,
      and Readmission reporting completeness. High-quality hospitals
      start at the 100-point mark.

  MRF Active Audit (from Rust scraper):
    • Auditor probes the baseline. Positive transparency metrics maintain
      or restore the 100-point limit, while failure modes (unreadable,
      WAF blocked) apply penalties that drop the score below 100.

  Final score is clamped to [0, 100].
"""

import sqlite3
import os
import sys

# ── path defaults (overridable via env for CI) ──────────────────────────────
AUDIT_DB    = os.environ.get("AUDIT_DB",    "web/public/audit_data.db")
SCRAPER_COMP_DB = os.environ.get("SCRAPER_COMP_DB", "scraper/compliance.db")
SCRAPER_PRICES_DB = os.environ.get("SCRAPER_PRICES_DB", "scraper/prices.db")


def ensure_audit_compliance_columns(conn: sqlite3.Connection) -> None:
    """
    Migrate audit_data.db's compliance table to include the Rust scraper
    columns if they are not yet present (safe ALTER TABLE migrations).
    """
    for col_def in [
        ("mrf_machine_readable", "INTEGER DEFAULT 1"),
        ("waf_blocked",          "INTEGER DEFAULT 0"),
        ("evidence_json",        "TEXT    DEFAULT ''"),
    ]:
        try:
            conn.execute(
                f"ALTER TABLE compliance ADD COLUMN {col_def[0]} {col_def[1]}"
            )
        except sqlite3.OperationalError:
            pass  # column already exists


def merge_compliance(conn: sqlite3.Connection, scraper_comp_db: str) -> int:
    """
    Pull active-audit columns from the Rust scraper's compliance.db and
    layer them on top of the CMS baseline scores already stored in audit_data.db.
    Returns the number of rows merged.
    """
    conn.execute(f"ATTACH DATABASE '{scraper_comp_db}' AS rust_comp")
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT ccn, txt_exists, robots_ok,
                   mrf_reachable, mrf_valid, mrf_fresh,
                   shoppable_exists, mrf_machine_readable,
                   waf_blocked, evidence_json
            FROM rust_comp.compliance
        """)
        rust_rows = cur.fetchall()

        merged = 0
        for row in rust_rows:
            (ccn, txt_exists, robots_ok, mrf_reach, mrf_val, mrf_fresh,
             sh_exists, mrf_mach, waf, ev_json) = row

            # Fetch the current CMS baseline score for this hospital
            cur.execute("SELECT score FROM compliance WHERE ccn = ?", (ccn,))
            baseline = cur.fetchone()
            if baseline is None:
                continue  # hospital not in our CMS data set — skip

            cms_base = baseline[0] or 0

            # Build MRF audit delta
            if waf:
                mrf_delta = -30  # active WAF block — credit txt_exists anyway
            elif txt_exists:
                mrf_delta = 55
            else:
                mrf_delta = 0

            mrf_delta += 10 if robots_ok else 0
            mrf_delta += -40 if not mrf_mach else 0

            final_score = max(0, min(100, cms_base + mrf_delta))

            conn.execute("""
                UPDATE compliance SET
                    score              = ?,
                    txt_exists         = ?,
                    robots_ok          = ?,
                    mrf_reachable      = ?,
                    mrf_valid          = ?,
                    mrf_fresh          = ?,
                    shoppable_exists   = ?,
                    mrf_machine_readable = ?,
                    waf_blocked        = ?,
                    evidence_json      = COALESCE(evidence_json, '') || ?
                WHERE ccn = ?
            """, (
                final_score,
                txt_exists, robots_ok, mrf_reach, mrf_val, mrf_fresh,
                sh_exists, mrf_mach, waf,
                (" | " + ev_json if ev_json else ""),
                ccn,
            ))
            merged += 1

        conn.commit()
        return merged
    finally:
        conn.execute("DETACH DATABASE rust_comp")


def merge_prices(conn: sqlite3.Connection, scraper_prices_db: str) -> int:
    """
    UPSERT prices from the Rust scraper's prices.db into audit_data.db.
    The scraper schema uses (ccn, cpt_code, description, payer, plan) as a
    natural key; the UI's prices table uses (ein, cpt_code, description) with
    ein == ccn. We normalise on the way in.
    Returns the number of rows upserted.
    """
    # Ensure the target prices table has the columns we're about to write
    conn.execute("""
        CREATE TABLE IF NOT EXISTS prices (
            hospital_name       TEXT,
            ein                 TEXT,
            cpt_code            TEXT,
            description         TEXT,
            cash_price          REAL,
            url                 TEXT,
            provider_npi        TEXT,
            attribution_confidence REAL
        )
    """)

    # Add missing columns if the table already existed with an older schema
    for col in [
        ("gross_charge",     "REAL"),
        ("min_negotiated",   "REAL"),
        ("max_negotiated",   "REAL"),
        ("payer",            "TEXT"),
        ("plan",             "TEXT"),
    ]:
        try:
            conn.execute(f"ALTER TABLE prices ADD COLUMN {col[0]} {col[1]}")
        except sqlite3.OperationalError:
            pass

    conn.execute(f"ATTACH DATABASE '{scraper_prices_db}' AS rust_prices")
    try:
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) FROM rust_prices.prices")
        src_count = cur.fetchone()[0]
        if src_count == 0:
            return 0

        # Pull from scraper and write to destination — map ccn → ein
        cur.execute("""
            INSERT OR REPLACE INTO prices
                (ein, cpt_code, description,
                 cash_price, gross_charge,
                 min_negotiated, max_negotiated,
                 payer, plan,
                 provider_npi, attribution_confidence)
            SELECT
                ccn, cpt_code, description,
                cash_price, gross_charge,
                min_negotiated, max_negotiated,
                payer, plan,
                provider_npi, attribution_confidence
            FROM rust_prices.prices
        """)
        conn.commit()
        return cur.rowcount
    finally:
        conn.execute("DETACH DATABASE rust_prices")


def print_score_distribution(conn: sqlite3.Connection) -> None:
    cur = conn.cursor()
    cur.execute("""
        SELECT
            SUM(CASE WHEN score  < 25 THEN 1 ELSE 0 END) as q0,
            SUM(CASE WHEN score >= 25 AND score < 50 THEN 1 ELSE 0 END) as q1,
            SUM(CASE WHEN score >= 50 AND score < 75 THEN 1 ELSE 0 END) as q2,
            SUM(CASE WHEN score >= 75 AND score < 100 THEN 1 ELSE 0 END) as q3,
            SUM(CASE WHEN score = 100 THEN 1 ELSE 0 END) as q4,
            MAX(score) as max_score,
            ROUND(AVG(score), 1) as avg_score
        FROM compliance
    """)
    row = cur.fetchone()
    print(f"\n  Score distribution (post-merge):")
    print(f"    0–24  (Non-reporting):   {row[0]:>6,}")
    print(f"    25–49 (Deficient):       {row[1]:>6,}")
    print(f"    50–74 (Partial):         {row[2]:>6,}")
    print(f"    75–99 (Compliant):       {row[3]:>6,}")
    print(f"    100   (Full):            {row[4]:>6,}")
    print(f"    Max score: {row[5]}   Avg score: {row[6]}")


def main() -> None:
    print("\n" + "=" * 55)
    print("  Healthspend · Pipeline Integration Agent")
    print("=" * 55)

    if not os.path.exists(AUDIT_DB):
        print(f"✗ Target database not found: {AUDIT_DB}")
        print("  Run ingest.py first to create the baseline database.")
        sys.exit(1)

    conn = sqlite3.connect(AUDIT_DB)
    conn.execute("PRAGMA journal_mode=WAL")

    # ── 1. Migrate compliance schema ────────────────────────────────────────
    print("\n[1/3] Migrating compliance schema for MRF audit columns…")
    ensure_audit_compliance_columns(conn)
    print("  ✓ Schema ready")

    # ── 2. Merge compliance scores ──────────────────────────────────────────
    print(f"\n[2/3] Merging MRF audit results from scraper/compliance.db…")
    if not os.path.exists(SCRAPER_COMP_DB):
        print(f"  ⚠  {SCRAPER_COMP_DB} not found — skipping (will run on CI where scraper ran first)")
    else:
        n = merge_compliance(conn, SCRAPER_COMP_DB)
        print(f"  ✓ Merged {n} active-audit records — scores now up to 100-point range")
        print_score_distribution(conn)

    # ── 3. Merge prices ─────────────────────────────────────────────────────
    print(f"\n[3/3] Pushing fresh prices from scraper/prices.db…")
    if not os.path.exists(SCRAPER_PRICES_DB):
        print(f"  ⚠  {SCRAPER_PRICES_DB} not found — skipping")
    else:
        n = merge_prices(conn, SCRAPER_PRICES_DB)
        if n == 0:
            print("  ⚠  Scraper prices.db is empty — nothing to merge")
        else:
            print(f"  ✓ Upserted {n} price rows into the public deployment payload")

    conn.close()
    print("\n" + "=" * 55)
    print("  ✓ Pipeline integration complete.")
    print("    audit_data.db is ready for Hugging Face upload.")
    print("=" * 55 + "\n")


if __name__ == "__main__":
    main()
