export interface CptEntry {
  code: string;
  plain: string;
  technical: string;
  category: string;
}

export const CPT_CATALOG: CptEntry[] = [
  { code: '99202', plain: 'New Patient Visit (brief)', technical: 'Office visit, new patient, 15-29m', category: 'Preventive' },
  { code: '99203', plain: 'New Patient Visit (standard)', technical: 'Office visit, new patient, 30-44m', category: 'Preventive' },
  { code: '99204', plain: 'New Patient Visit (detailed)', technical: 'Office visit, new patient, 45-59m', category: 'Preventive' },
  { code: '99205', plain: 'New Patient Visit (complex)', technical: 'Office visit, new patient, 60-74m', category: 'Preventive' },
  { code: '99212', plain: 'Office Visit (brief)', technical: 'Office visit, established patient, 10-19m', category: 'Preventive' },
  { code: '99213', plain: 'Doctor Office Visit (est)', technical: 'Office visit, established patient, 20-29m', category: 'Preventive' },
  { code: '99214', plain: 'Doctor Office Visit (long)', technical: 'Office visit, established patient, 30-39m', category: 'Preventive' },
  { code: '99215', plain: 'Doctor Office Visit (complex)', technical: 'Office visit, established patient, 40-54m', category: 'Preventive' },
  { code: '99391', plain: 'Well-Baby Exam (<1 yr)', technical: 'Preventive visit, infant', category: 'Preventive' },
  { code: '99392', plain: 'Well-Child Exam (1-4 yrs)', technical: 'Preventive visit, early childhood', category: 'Preventive' },
  { code: '99393', plain: 'Well-Child Exam (5-11 yrs)', technical: 'Preventive visit, late childhood', category: 'Preventive' },
  { code: '99394', plain: 'Well-Teen Exam (12-17 yrs)', technical: 'Preventive visit, adolescent', category: 'Preventive' },
  { code: '99395', plain: 'Annual Physical (adult)', technical: 'Preventive visit, 18–39 years', category: 'Preventive' },
  { code: '99396', plain: 'Annual Physical (40s–50s)', technical: 'Preventive visit, 40–64 years', category: 'Preventive' },
  { code: '99397', plain: 'Annual Physical (senior)', technical: 'Preventive visit, 65+ years', category: 'Preventive' },
  { code: '90686', plain: 'Flu Shot (adult)', technical: 'Influenza vaccine, 4-valent', category: 'Preventive' },
  { code: '96372', plain: 'Injection / Shot', technical: 'Therapeutic injection, subcutaneous/IM', category: 'Preventive' },
  { code: 'G0438', plain: 'Medicare Annual Wellness Visit (first)', technical: 'Annual wellness visit, initial', category: 'Preventive' },
  { code: 'G0439', plain: 'Medicare Annual Wellness Visit (subsequent)', technical: 'Annual wellness visit, subsequent', category: 'Preventive' },
  { code: '99281', plain: 'ER Visit (minor)', technical: 'Emergency dept visit, low complexity', category: 'Emergency' },
  { code: '99282', plain: 'ER Visit (low)', technical: 'Emergency dept visit, straightforward', category: 'Emergency' },
  { code: '99283', plain: 'Emergency Room', technical: 'Emergency dept visit, moderate complexity', category: 'Emergency' },
  { code: '99284', plain: 'ER Visit (serious)', technical: 'Emergency dept visit, high complexity', category: 'Emergency' },
  { code: '99285', plain: 'ER Visit (life-threatening)', technical: 'Emergency dept visit, highest complexity', category: 'Emergency' },
  { code: '99291', plain: 'Critical Care (first hour)', technical: 'Critical care, first 30–74 mins', category: 'Emergency' },
  { code: '70450', plain: 'Head CT Scan', technical: 'CT head/brain without contrast', category: 'Imaging' },
  { code: '70470', plain: 'Head CT (with dye)', technical: 'CT head/brain with contrast', category: 'Imaging' },
  { code: '70486', plain: 'Sinus CT Scan', technical: 'CT maxillofacial area w/o contrast', category: 'Imaging' },
  { code: '70551', plain: 'Brain MRI', technical: 'MRI brain without contrast', category: 'Imaging' },
  { code: '70553', plain: 'Brain MRI (with dye)', technical: 'MRI brain with and without contrast', category: 'Imaging' },
  { code: '71045', plain: 'Chest X-Ray', technical: 'X-ray chest, 1 view', category: 'Imaging' },
  { code: '71046', plain: 'Chest X-Ray (2 views)', technical: 'X-ray chest, 2 views', category: 'Imaging' },
  { code: '71250', plain: 'Chest CT Scan', technical: 'CT thorax without contrast', category: 'Imaging' },
  { code: '71260', plain: 'Chest CT Scan (with dye)', technical: 'CT thorax with contrast', category: 'Imaging' },
  { code: '72100', plain: 'Lower Back X-Ray', technical: 'X-ray exam of lower spine, 2/3 views', category: 'Imaging' },
  { code: '72125', plain: 'Neck CT Scan', technical: 'CT neck spine without contrast', category: 'Imaging' },
  { code: '72141', plain: 'Neck MRI', technical: 'MRI neck spine without contrast', category: 'Imaging' },
  { code: '72148', plain: 'Lower Back MRI', technical: 'MRI lumbar spine without contrast', category: 'Imaging' },
  { code: '72158', plain: 'Lower Back MRI (with dye)', technical: 'MRI lumbar spine with and without contrast', category: 'Imaging' },
  { code: '72170', plain: 'Pelvis X-Ray', technical: 'X-ray pelvis, 1 or 2 views', category: 'Imaging' },
  { code: '73030', plain: 'Shoulder X-Ray', technical: 'X-ray exam of shoulder', category: 'Imaging' },
  { code: '73221', plain: 'Arm/Joint MRI', technical: 'MRI joint of upper extremity', category: 'Imaging' },
  { code: '73630', plain: 'Foot X-Ray', technical: 'X-ray exam of foot', category: 'Imaging' },
  { code: '73721', plain: 'Knee MRI', technical: 'MRI knee without contrast', category: 'Imaging' },
  { code: '74150', plain: 'Abdomen CT Scan', technical: 'CT abdomen without contrast', category: 'Imaging' },
  { code: '74176', plain: 'Abdomen & Pelvis CT', technical: 'CT abdomen and pelvis w/o contrast', category: 'Imaging' },
  { code: '74177', plain: 'CT Scan', technical: 'CT abdomen and pelvis w/ contrast', category: 'Imaging' },
  { code: '74178', plain: 'CT Scan (full body)', technical: 'CT abdomen and pelvis w/ & w/o contrast', category: 'Imaging' },
  { code: '76700', plain: 'Abdominal Ultrasound', technical: 'US abdomen, real time', category: 'Imaging' },
  { code: '76705', plain: 'Abdominal Ultrasound (limited)', technical: 'US abdomen, real time, limited', category: 'Imaging' },
  { code: '76805', plain: 'Prenatal Ultrasound', technical: 'OB ultrasound, after first trimester', category: 'Imaging' },
  { code: '76815', plain: 'Pregnancy Ultrasound (quick)', technical: 'Ultrasound, pregnant uterus, limited', category: 'Imaging' },
  { code: '76830', plain: 'Transvaginal Ultrasound', technical: 'Ultrasound, transvaginal', category: 'Imaging' },
  { code: '77066', plain: 'Mammogram (diagnostic)', technical: 'Bilateral diagnostic mammography', category: 'Imaging' },
  { code: '77067', plain: 'Mammogram (screening)', technical: 'Screening mammography, bilateral', category: 'Imaging' },
  { code: 'G0204', plain: 'Screening Mammogram (3D)', technical: 'Diagnostic mammography, including CAD', category: 'Imaging' },
  { code: '80048', plain: 'Basic Blood Panel', technical: 'Metabolic panel, basic', category: 'Lab Work' },
  { code: '80050', plain: 'General Health Panel', technical: 'General health panel', category: 'Lab Work' },
  { code: '80053', plain: 'Metabolic Panel', technical: 'Comprehensive metabolic panel', category: 'Lab Work' },
  { code: '80061', plain: 'Cholesterol / Lipid Panel', technical: 'Lipid panel', category: 'Lab Work' },
  { code: '81001', plain: 'Urinalysis', technical: 'Urinalysis with microscopy', category: 'Lab Work' },
  { code: '81002', plain: 'Urinalysis (dipstick)', technical: 'Urinalysis without microscopy', category: 'Lab Work' },
  { code: '82306', plain: 'Vitamin D Test', technical: 'Vitamin D; 25 hydroxy', category: 'Lab Work' },
  { code: '82728', plain: 'Iron Test', technical: 'Ferritin', category: 'Lab Work' },
  { code: '82947', plain: 'Blood Sugar Test (Glucose)', technical: 'Glucose; quantitative, blood', category: 'Lab Work' },
  { code: '83036', plain: 'Diabetes A1C Test', technical: 'Hemoglobin A1c', category: 'Lab Work' },
  { code: '83735', plain: 'Magnesium Test', technical: 'Magnesium', category: 'Lab Work' },
  { code: '84153', plain: 'PSA (Prostate) Test', technical: 'PSA; total', category: 'Lab Work' },
  { code: '84439', plain: 'Thyroid Test (Free T4)', technical: 'Thyroxine; free', category: 'Lab Work' },
  { code: '84443', plain: 'Thyroid Test (TSH)', technical: 'Thyroid stimulating hormone', category: 'Lab Work' },
  { code: '85025', plain: 'Complete Blood Count (CBC)', technical: 'Blood count, complete (CBC) w/ auto diff', category: 'Lab Work' },
  { code: '85610', plain: 'Blood Clotting Test (PT)', technical: 'Prothrombin time', category: 'Lab Work' },
  { code: '86580', plain: 'TB Skin Test', technical: 'Tuberculosis intradermal test', category: 'Lab Work' },
  { code: '87086', plain: 'Urine Culture', technical: 'Culture, bacterial; quantitative colony count', category: 'Lab Work' },
  { code: '87491', plain: 'Chlamydia Test', technical: 'Infectious agent detection by nucleic acid (DNA or RNA); Chlamydia trachomatis, amplified probe technique', category: 'Lab Work' },
  { code: '87502', plain: 'COVID-19 Test', technical: 'Detection, SARS-CoV-2', category: 'Lab Work' },
  { code: '87591', plain: 'Gonorrhea Test', technical: 'Infectious agent detection by nucleic acid (DNA or RNA); Neisseria gonorrhoeae, amplified probe technique', category: 'Lab Work' },
  { code: '87804', plain: 'Flu Test', technical: 'Detection, influenza virus A/B', category: 'Lab Work' },
  { code: '87880', plain: 'Strep Test (rapid)', technical: 'Infectious agent detection by immunoassay with direct optical observation; Streptococcus, group A', category: 'Lab Work' },
  { code: '12001', plain: 'Stitches', technical: 'Simple laceration repair, <2.5cm', category: 'Surgery' },
  { code: '12011', plain: 'Stitches (face/ears)', technical: 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 2.5 cm or less', category: 'Surgery' },
  { code: '17000', plain: 'Wart/Lesion Removal', technical: 'Destruction (eg, laser surgery, electrosurgery, cryosurgery, chemosurgery, surgical curettement), premalignant lesions', category: 'Surgery' },
  { code: '19301', plain: 'Breast Lump Removal', technical: 'Partial mastectomy', category: 'Surgery' },
  { code: '27130', plain: 'Hip Replacement', technical: 'Total hip arthroplasty', category: 'Surgery' },
  { code: '27447', plain: 'Knee Replacement', technical: 'Total knee arthroplasty', category: 'Surgery' },
  { code: '29881', plain: 'Knee Scope (meniscus)', technical: 'Arthroscopy knee with meniscectomy', category: 'Surgery' },
  { code: '32663', plain: 'Lung Surgery (scope)', technical: 'Thoracoscopic lobectomy', category: 'Surgery' },
  { code: '42440', plain: 'Tonsil Removal', technical: 'Excision of submandibular gland', category: 'Surgery' },
  { code: '42820', plain: 'Tonsil & Adenoid Removal (<12)', technical: 'Tonsillectomy and adenoidectomy; younger than age 12', category: 'Surgery' },
  { code: '43239', plain: 'Upper GI Scope (biopsy)', technical: 'Upper GI endoscopy with biopsy', category: 'Surgery' },
  { code: '43249', plain: 'Upper GI Scope (balloon)', technical: 'Esophagogastroduodenoscopy, flexible, transoral; with transendoscopic balloon dilation of esophagus', category: 'Surgery' },
  { code: '45378', plain: 'Colonoscopy', technical: 'Colonoscopy, diagnostic', category: 'Surgery' },
  { code: '45380', plain: 'Colonoscopy (with biopsy)', technical: 'Colonoscopy with biopsy', category: 'Surgery' },
  { code: '45385', plain: 'Colonoscopy (snare removal)', technical: 'Colonoscopy, flexible; with removal of tumor(s), polyp(s), or other lesion(s) by snare technique', category: 'Surgery' },
  { code: '47562', plain: 'Gallbladder Removal', technical: 'Laparoscopic cholecystectomy', category: 'Surgery' },
  { code: '49505', plain: 'Hernia Repair', technical: 'Inguinal hernia repair', category: 'Surgery' },
  { code: '66984', plain: 'Cataract Surgery', technical: 'Cataract removal with lens implant', category: 'Surgery' },
  { code: '69436', plain: 'Ear Tubes (child)', technical: 'Tympanostomy under general anesthesia', category: 'Surgery' },
  { code: '59400', plain: 'Childbirth', technical: 'Routine OB care, vaginal delivery', category: 'Maternity' },
  { code: '59409', plain: 'Vaginal Birth (delivery only)', technical: 'Vaginal delivery only', category: 'Maternity' },
  { code: '59510', plain: 'C-Section', technical: 'Routine OB care, cesarean delivery', category: 'Maternity' },
  { code: '59514', plain: 'C-Section (delivery only)', technical: 'Cesarean delivery only', category: 'Maternity' },
  { code: '54300', plain: 'Circumcision', technical: 'Plastic operation of penis for straightening of chordee', category: 'Maternity' },
  { code: '93000', plain: 'EKG / Heart Tracing', technical: 'Electrocardiogram with interpretation', category: 'Cardiology' },
  { code: '93015', plain: 'Heart Stress Test', technical: 'Cardiovascular stress test', category: 'Cardiology' },
  { code: '93306', plain: 'Heart Ultrasound (echo)', technical: 'Echocardiography with Doppler', category: 'Cardiology' },
  { code: '90791', plain: 'Psychiatric Evaluation', technical: 'Psychiatric diagnostic evaluation', category: 'Mental Health' },
  { code: '90832', plain: 'Therapy Session (30 min)', technical: 'Psychotherapy, 30 minutes', category: 'Mental Health' },
  { code: '90834', plain: 'Therapy Session (45 min)', technical: 'Psychotherapy, 45 minutes', category: 'Mental Health' },
  { code: '90837', plain: 'Therapy Session (60 min)', technical: 'Psychotherapy, 60 minutes', category: 'Mental Health' },
  { code: '90847', plain: 'Family Therapy Session', technical: 'Family psychotherapy', category: 'Mental Health' },
  { code: '97110', plain: 'Physical Therapy Exercise', technical: 'Therapeutic exercises, per 15 min', category: 'Physical Therapy' },
  { code: '97530', plain: 'Therapeutic Activities', technical: 'Therapeutic activities, per 15 min', category: 'Physical Therapy' },
  { code: '95806', plain: 'Home Sleep Test', technical: 'Sleep study, unattended', category: 'Sleep' },
  { code: '95810', plain: 'Sleep Study (overnight)', technical: 'Polysomnography, full monitoring', category: 'Sleep' },
];

export const CPT_CATEGORIES = [
  'Emergency', 'Imaging', 'Lab Work', 'Surgery',
  'Maternity', 'Cardiology', 'Mental Health',
  'Physical Therapy', 'Preventive', 'Sleep'
];

export const PLAIN_TO_CODE: Record<string, string> = Object.fromEntries(
  CPT_CATALOG.map(e => [e.plain.toLowerCase(), e.code])
);

export const CODE_TO_PLAIN: Record<string, string> = Object.fromEntries(
  CPT_CATALOG.map(e => [e.code, e.plain])
);
